:Author: aswana
:Email: {AuthorEmail}
:Date: 11/04/2019
:Revision: version#
:License: Public Domain

= Project: {Project}

Project Overview

== Step 1: Installation
For this project, we will build a simple digital code lock that users can enter and key in. In this tutorial, we will show users how a digital code lock system works in an Arduino Interface.

- By the end of this tutorial you will be able to :
- Set up a digital code lock with Zio and basic 12 keys keypad
- Be able to interface with Arduino IDE to program Zio with keypad
- Create a program that asks users to enter a six-digit password to unlock 
- Be able to create a new six-digit password


== Step 2: Assemble the circuit

Assemble the circuit following the diagram schematics.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 Digital_Code_Locker                => Arduino sketch folder
  ├── digital_code_locker.ino       => main Arduino file
  ├── schematics.png                => an image of the required schematics
  ├── unotokeypadlayout.png         => an image of the keypad to Uno connection layout
  └── ReadMe.adoc                   => this file
....

=== License
This project is released under a {License} License.

=== BOM

|===
Part name                           |Quantity
Zuino M Uno                         | 1
Zio Qwiic 0.91" OLED Display        | 1
4x3 Keypad                          | 1
Male to Female Jumper Wires         | 7
200mm Qwiic Cables                  | 1
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
